### PR TITLE
Various small changes + create systemd timers

### PR DESCRIPTION
**Pull request by Exchizz**
Hi,

I've made some changes to your role that I think you might like. I have the use case where I want to run a script before running rsnapshot (I want to ensure the src/dst directories are mountpoints and mount a ceph snapshot). Given the script for the two backup points are not the same, I decided to split my two backup points into two different rsync instances and let systemd run the script as preExec. Furthermore, the playbook adds a systemd service and timers to let systemd handle when a backup should be run.

This PR makes the following changes:

1. Allow options to be set for each backup point ( see example further down )
2. Create systemd .service and .timers for hour, daily, weekly and hourly backups - can be disabled by setting "enable_systemd_timers" to false.
3. Allows disabling retain periods from the playbook by setting  the value to -1 ( see example )
4. Adds a variable for disabling file logging
5. Allows to change the rsync config path from the playbook ( nice if multiple rsync instances are run )

Example config:
```
tasks:
  - include_role:
       name: ansible-rsnapshot
     vars:
       - rsnapshot_systemd_postfix: "_projectX"
       - rsnapshot_config_file: /etc/rsnapshot_projectX.conf
       - rsnapshot_lockfile: "/var/run/rsnapshot_projectX.pid"
       - rsnapshot_snapshot_root: "/mnt/bkup_dst/"
       - rsnapshot_backup_points:
         - dir: '/mnt/ProjectX_src/'
           host: 'HostA'
           options: '+rsync_long_args=--no-relative'
       - rsnapshot_retain_monthly: 6
       - rsnapshot_retain_weekly: 4
       - rsnapshot_retain_daily: 7
       - rsnapshot_retain_hourly: -1 # note, hourly backups are not run)
       - rsnapshot_link_dest: 0
       - rsnapshot_systemd_preexec: "/usr/local/sbin/preScript.sh"
       - rsnapshot_systemd_postexec: "/usr/local/sbin/PostScript.sh"
       - rsnapshot_systemd_onfailure: "/usr/local/sbin/failureScript.sh"
       - rsnapshot_verbose: "3"
```

Please let me know if you don't like some of the changes.

### CODE REVIEW

**Comment by tutunak** [comment]
Hi @vbotka ! Why haven't you merged this pull request yet?

**Review by vbotka — COMMENTED** [review]
'rsnapshot_config_file' depends on the OS. It's not possible to move it into the 'defaults'. See 'tasks/vars.yml' how OS-dependent variables are created. Put customized OS-dependent variables into the directory 'vars'.

**Comment by tutunak** [comment]
@Exchizz can you do these changes?

**Comment by Exchizz** [comment]
Done - I'm not aware if any other variables should be moved.

**Comment by vbotka** [comment]
> @Exchizz can you do these changes?

Thank you for the comments, Dmitry! I've finally managed to start reviewing the patches.

Thank you for your contribution,  Mathias! Sorry for the delay. I'm working on it now. Let me complete the whole review. Some patches will be accepted right now. But, there must be also some changes. Please let me finish the review. I'll come back to you with the summary today.

**Review by vbotka — APPROVED** [review]
OK.

**Comment by vbotka** [comment]
Hi Mathias! I've accepted all PR into the 'devel' branch and made some changes:

    * File renamed to tasks/systemd-timers.yml
    * Variable 'enable_systemd_timers' renamed to 'rsnapshot_systemd_timers'
    * Variable 'rsnapshot_systemd_timers' depends on OS. Moved to vars/defaults/*
    * Default 'rsnapshot_systemd_timers: false'. Backward compatible. Do
      not break crontab installations.
    * Debug updated
    * Added tags rsnapshot_systemd_timers, rsnapshot_systemd_timers_*
    * Truthy values changed to true/false because of .yamllint
    * Cleanup, comments, and formatting
    * Removed condition from 'Install rsnapshot timers'. Create all timers.
    * Added 'Disable rsnapshot timers'
    * Fixed conditions 'lookup/vars'
    * Get and display timers when 'rsnapshot_debug=true'

I've tested the role with Ubuntu 20.04 with `rsnapshot_systemd_timers: false` only. Would it be possible to review the changes and potentially test it? Let me know if you have any questions.

Thank you,

 -vlado

**Comment by vbotka** [comment]
The problem with the custom configuration files for timers hasn't been resolved yet,e.g. rsnapshot_systemd_postfix: "_projectX". It will be necessary to separate the configuration of the timers from the default configuration, I think. Do you have any idea?

**Comment by vbotka** [comment]
The problem with systemd configuration has been solved. The tasks systemd*, configure.yml, and templates have been updated to accept the configuration loop from the dictionary rsnapshot_systemd_conf. Please review the changes
```
    * systemd example in README updated
    * Changed structure of systemd config dictionary rsnapshot_systemd_conf d({})
    * Added var rsnapshot_snapshot_root_create d(true)
    * Renamed var -rsnapshot_systemd_timers to rsnapshot_systemd d(false)
    * Moved var rsnapshot_systemd from vars/defaults/* to default/main.yml
    * Loop enabled configure.yml and templates
    * Updated debug.yml
    * Renamed task to systemd.yml and split to systemd-conf.yml and systemd-service.yml
    * Tested with Ubuntu 20.04
```
The test with Ubuntu 20.04 failed to start the timers

> failed: [plana] (item=monthly) => {"ansible_loop_var": "item", "changed": false, "item": "monthly", "msg": "Unable to start service /etc/systemd/system/rsnapshot_projectX-monthly.timer: Failed to start etc-systemd-system-rsnapshot_projectX\\x2dmonthly.timer.mount: Unit etc-systemd-system-rsnapshot_projectX\\x2dmonthly.timer.mount not found.\n"}

See the [full log](https://gist.github.com/vbotka/b2142c1688bd92e14c5ec2c2e57e02bc)

Would it be possible to help me to resolve this problem?

**Comment by Exchizz** [comment]
Yes sure, I will get back to you

**Comment by Exchizz** [comment]
In some of the files, you prepend the variables with "conf." such as "conf.rsnapshot_config_file". The role fails to install due to not all variables have conf. prepended.

Do you want all variables to start with conf.... ?  :)

EDIT:
Why do you create /usr/local/etc/rsnapshot.conf when /etc/rsnapshot_projectX.conf is also created ?

**Comment by Exchizz** [comment]
> The problem with systemd configuration has been solved. The tasks systemd*, configure.yml, and templates have been updated to accept the configuration loop from the dictionary rsnapshot_systemd_conf. Please review the changes
> 
> ```
>     * systemd example in README updated
>     * Changed structure of systemd config dictionary rsnapshot_systemd_conf d({})
>     * Added var rsnapshot_snapshot_root_create d(true)
>     * Renamed var -rsnapshot_systemd_timers to rsnapshot_systemd d(false)
>     * Moved var rsnapshot_systemd from vars/defaults/* to default/main.yml
>     * Loop enabled configure.yml and templates
>     * Updated debug.yml
>     * Renamed task to systemd.yml and split to systemd-conf.yml and systemd-service.yml
>     * Tested with Ubuntu 20.04
> ```
> 
> The test with Ubuntu 20.04 failed to start the timers
> 
> > failed: [plana] (item=monthly) => {"ansible_loop_var": "item", "changed": false, "item": "monthly", "msg": "Unable to start service /etc/systemd/system/rsnapshot_projectX-monthly.timer: Failed to start etc-systemd-system-rsnapshot_projectX\x2dmonthly.timer.mount: Unit etc-systemd-system-rsnapshot_projectX\x2dmonthly.timer.mount not found.\n"}
> 
> See the [full log](https://gist.github.com/vbotka/b2142c1688bd92e14c5ec2c2e57e02bc)
> 
> Would it be possible to help me to resolve this problem?

(I'm not really sure how to add the commit properly to this pull request)
I can successfully install rsnapshot on ubuntu 20.04 when I add conf. to some of the variables (as mentioned above) and when applying the following commit to fix the systemd enable error:
dc445be5488fcd22fbdf1968e600f7b15f5a2efc

**Comment by vbotka** [comment]
> Why do you create /usr/local/etc/rsnapshot.conf when /etc/rsnapshot_projectX.conf is also created ?

The main idea of all the changes I've made is to "run the role once" to configure both user-space (/usr/local/etc/rsnapshot.conf ) and systemd (/etc/rsnapshot_projectX.conf, when enabled). Make the role robust, backward-compatible, and easier both to use and maintain.

The default values of the user-space configuration are also used to configure systemd. The task configure.yml and the template rsnapshot.conf.j2 are shared. This makes both the usage and maintenance easier. By default the configuration of systemd is disabled (rsnapshot_systemd: false). This makes all the changes introduced by this feature backward compatible.

**Comment by vbotka** [comment]
> In some of the files, you prepend the variables with "conf." such as "conf.rsnapshot_config_file". 
> The role fails to install due to not all variables have conf. prepended.
> Do you want all variables to start with conf.... ? :)

Short answer: No. The variable "conf" is dynamically created :)

Details:

See tasks/systemd.yml
```
- name: "systemd: Create configuration"
  include_tasks: systemd-conf.yml
  loop: "{{ rsnapshot_systemd_conf|dict2items }}"
  loop_control:
    loop_var: oitem
  vars:
    rsnapshot_config_file: "{{ '/etc/rsnapshot_' ~  oitem.key ~ '.conf' }}"
    postfix: "{{ oitem.key }}"
    conf: "{{ oitem.value }}"
  tags: rsnapshot_systemd_conf
```
The purpose of this task is to prepare the necessary local variables and loop the dictionary rsnapshot_systemd_conf. The dictionary rsnapshot_systemd_conf can keep configuration of more systemd projects.

See tasks/systemd-conf.yml
```
- name: "systemd-conf: Debug"
  ...
- name: "systemd-conf: Configure {{ postfix }}"                                               
  include_tasks: configure.yml
```
The purpose of this task is to display the debug only and include configure.yml

See tasks/configure.yml
```
...
- name: "configure: Create configuration {{ rsnapshot_config_file }}"                         
  template:                                                                                   
    src: rsnapshot.conf.j2                                                                    
    dest: "{{ rsnapshot_config_file }}"                                                       
    owner: "{{ conf.rsnapshot_config_file_owner|default(rsnapshot_config_file_owner) }}"      
    group: "{{ conf.rsnapshot_config_file_group|default(rsnapshot_config_file_group) }}"      
    mode: "{{ conf.rsnapshot_config_file_mode|default(rsnapshot_config_file_mode) }}"         
    backup: "{{ rsnapshot_backup_conf }}"                                                     
    validate: "rsnapshot -c %s configtest"
```
The purpose of this task is to share the code to configure both user-space (default values) and systemd (values in the conf dictionary; coming from the the dictionary rsnapshot_systemd_conf).

**Comment by vbotka** [comment]
> The role fails to install due to not all variables have conf. prepended.

This should not happen. My intention is to "default" filter all conf.* attributes. Have I omitted any such variable? Would it be possible to share the error?

**Comment by Exchizz** [comment]
> > The role fails to install due to not all variables have conf. prepended.
> 
> This should not happen. My intention is to "default" filter all conf.* attributes. Have I omitted any such variable? Would it be possible to share the error?

ah I get it :)
```
TASK [ansible-rsnapshot : configure: Create directory {{ conf.rsnapshot_snapshot_root| default(rsnapshot_snapshot_root) }}] **************************************************************************************************************************************************************************************************
fatal: [box]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'conf' is undefined\n\nThe error appears to have been in '/...../ansible-rsnapshot/tasks/configure.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"configure: Create directory {{ conf.rsnapshot_snapshot_root|\n  ^ here\nThis one looks easy to fix.  It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote.  For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}
```

**Comment by vbotka** [comment]
> (I'm not really sure how to add the commit properly to this pull request)
> [dc445be](rshttps://github.com/vbotka/ansible-rsnapshot/commit/dc445be5488fcd22fbdf1968e600f7b15f5a2efc)

See tasks/systemd-service.yml how the variables "rsnapshot_systemd_name, postfix , conf" are used.

**Comment by vbotka** [comment]
In the log of the test box I can see:

> May 14 12:00:00 localhost systemd[370463]: rsnapshot_projectX@hourly.service: Failed to execute command: No such file or directory 
May 14 12:00:00 localhost systemd[370463]: rsnapshot_projectX@hourly.service: Failed at step EXEC spawning /usr/local/sbin/preScript.sh: No such file or directory

It would help if you checkout "devel", create the scripts, and test it.

**Comment by vbotka** [comment]
> TASK [ansible-rsnapshot : configure: Create directory {{ conf.rsnapshot_snapshot_root| default(rsnapshot_snapshot_root) }}] **************************************************************************************************************************************************************************************************
> fatal: [box]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: **'conf' is undefined**\n\nThe error appears to have been in '/...../ansible-rsnapshot/tasks/configure.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"configure: Create directory {{ conf.rsnapshot_snapshot_root|\n  ^ here\nThis one looks easy to fix.  It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote.  For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}

I can't reproduce the problem. I see no problem with the name of the task  split to 2 lines.

tasks/configure.yml
```
- name: "configure: Create directory {{ conf.rsnapshot_snapshot_root|
                                        default(rsnapshot_snapshot_root) }}"
  file:
    state: directory
    ...
```

**Pull request merged**
